FROM rust:1.92-slim-bookworm

WORKDIR /app

RUN apt-get update && apt-get install -y pkg-config libssl-dev curl && rm -rf /var/lib/apt/lists/*
RUN cargo install cargo-watch

EXPOSE 8000

CMD ["cargo", "watch", "-x", "run --bin agents-server"]
